language: java
jdk: oraclejdk8
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "markoniemi-github"
    token: $SONAR_CLOUD_TOKEN
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean deploy org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar --settings settings.xml
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'