language: java
jdk: oraclejdk8
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "markoniemi-github"
    token: $SONAR_CLOUD_TOKEN
script:
  # mvn clean package deploy --settings settings.xml
  mvn clean install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
