version: 2
jobs:
  build:
    working_directory: ~/selenium-test-rule
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run: apt-get update; apt-get install openjfx
      - checkout
      - restore_cache:
          key: selenium-test-rule-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: selenium-test-rule-{{ checksum "pom.xml" }}
      - run: mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: selenium-test-rule-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_test_results:
          path: target/failsafe-reports
